Suburbs = [ 
	"petersham-nsw-2049",
	"lewisham-nsw-2049",
	"ashfield-nsw-2131",
	"rosebery-nsw-2018",
	"parramatta-nsw-2150",
	"auburn-nsw-2144",
	"clyde-nsw-2142",
	"granville-nsw-2142",
	"burwood-nsw-2134",
	"petersham-nsw-2049",
	"strathfield-nsw-2135",
	"lidcombe-nsw-2141",
	"homebush-nsw-2140",
	"homebush-west-nsw-2140",
	"rhodes-nsw-2138",
	"meadowbank-nsw-2114",
	"north-strathfield-nsw-2137",
	"concord-west-nsw-2138"
]

Availability = 2025-06-24T00:00:00Z
MaxDistance = 25.0
TempFolder = "./temp/"
IncludeNearbySuburbs = 0
